"""Google Sheet CASE 工作表欄位設定。"""

CASE_NO = "CASE_NO"
CREATED_AT = "CREATED_AT"
UPDATED_AT = "UPDATED_AT"
CLOSED_AT = "CLOSED_AT"
PRODUCT_TYPE = "PRODUCT_TYPE"
PART_NO = "PART_NO"
QTY = "QTY"
SITUATION = "SITUATION"
ORIGINAL_CART = "ORIGINAL_CART"
NOTE = "NOTE"
STAGE = "STAGE"
FINAL_RESOLUTION = "FINAL_RESOLUTION"
LAYER = "LAYER"
FLOOR = "FLOOR"
HANDLER = "HANDLER_NAME"
SHELVING_STATUS = "SHELVING_STATUS"

REQUIRED_SOURCE_COLUMNS: tuple[str, ...] = (
    CASE_NO,
    CREATED_AT,
    PART_NO,
    QTY,
    SITUATION,
    ORIGINAL_CART,
    STAGE,
    LAYER,
    FLOOR,
)

OPTIONAL_SOURCE_COLUMNS: tuple[str, ...] = (
    UPDATED_AT,
    CLOSED_AT,
    PRODUCT_TYPE,
    NOTE,
    HANDLER,
    FINAL_RESOLUTION,
    SHELVING_STATUS,
)

ALL_SOURCE_COLUMNS: tuple[str, ...] = (
    *REQUIRED_SOURCE_COLUMNS,
    *OPTIONAL_SOURCE_COLUMNS,
)

# TODO: CASE 工作表目前未提供的欄位會補成空值，畫面對應格維持空白。
# 待 CLOSED_AT 與 HANDLER 的資料來源確認後，只需更新本檔與資料來源。
